"""Assemble the artefacts an outside reviewer needs into one file.

    python tools/make_review_pack.py > docs/REVIEW_PACK.md

Generated rather than written so the quoted artefacts are byte-identical to the tree and the
pack can be regenerated after any change. Nothing here is a summary of the artefacts — the
artefacts are pasted whole, because a reviewer asked to judge a rule needs the rule.
"""

from __future__ import annotations

import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[1]

#: Grouped by slot, because the slot is now the point: one policy per run, tactics called
#: when their precondition holds, experience only in the experience arm. Until 2026-08-02 all of
#: these competed for a single slot, which measured the difference between kinds of intervention
#: rather than between policies.
#:
#: The second element is what the card is TRYING TO ACHIEVE, in our words, so a reviewer can
#: judge the text against its own intention. No result from our runs appears anywhere in this
#: pack: a policy has to be defensible as a policy.
CARDS = [
    ("policy", "policy-reactive",
     "Derive terms from the contract's own words and the record's own vocabulary, widen along "
     "one axis at a time after a miss, and stop only when you can name what a further search "
     "would have to find AND say which possible sources you did not cover."),
    ("policy", "policy-information-gain",
     "Choose each next action by what it could change — about the answer, the sufficiency of "
     "the evidence under it, an open conflict, or what remains uncertain."),
    ("policy", "policy-hypothesis-set",
     "Before searching, read the contract's numbered decision rules as a list of ROUTES to an "
     "answer, then close each one by confirming it or ruling it out — and report an excluded "
     "route as plainly as a confirmed one."),
    ("tactic", "tactic-query-formulation",
     "Build the term list from what the ANSWER must say rather than from the topic of the "
     "record; choose a query width deliberately and react to what returns; treat a search as a "
     "locator and never as a finding."),
    ("tactic", "tactic-coverage-pool",
     "Assemble a denominator over the source classes the current claim's proof obligation "
     "requires, so a later statement about coverage rests on something stateable."),
    ("tactic", "tactic-follow-dependency",
     "When a source defers its own conclusion or names another, follow it to where the question "
     "was settled."),
    ("tactic", "tactic-orient-from-summary",
     "Enter at a summarising document to learn the shape of the case and its local vocabulary "
     "cheaply, then move upstream to the records that establish things."),
    ("tactic", "tactic-counterevidence",
     "Once a candidate exists, spend a bounded effort trying to OVERTURN it — an earlier "
     "qualifying source, support for a named alternative, a temporal conflict, a different "
     "subject or episode, a reading that undoes yours."),
    ("tactic", "tactic-sample-unknown-types",
     "When a class of document is numerous or well-placed in time but its name does not say "
     "what it holds, open a few across its span and write down what the class IS."),
    ("experience", "experience-adapter",
     "When a term list and a type prior HAVE been supplied, work them first because they are "
     "cheap, then test them against this record, and treat a disagreement as a fact about the "
     "prior."),
    ("general", "tool-contract",
     "State what the instruments actually do, identically for every arm, so no policy competes "
     "on knowing the tool better than another."),
]

SPEC = site.specs_root() / "STORE.390.date_of_initial_diagnosis.yaml"

HEAD = """# Review pack — one task contract, three policies, six tactics

Generated by `tools/make_review_pack.py` at commit `{sha}`. Everything below is pasted verbatim
from the repository.
from acr.core import site


## What this is

An agentic chart-review system. A model is given a **task contract** (what the answer must mean)
and a **search strategy card** (how to move through the record), plus seven tools over one
patient's documents. It reads, cites, and submits an answer.

Cancer registry abstraction is the use case under test; the architecture is meant to be
domain-neutral, so a rule that only makes sense for oncology is a defect.

**The three factors are meant to vary independently:**

| factor | where it lives | status |
|---|---|---|
| task contract | `assets/specs/*.yaml` | independent |
| search policy | `assets/skills/policy-*` (one per run) + `tactic-*` (called on precondition) | independent, slot-assembled |
| prior experience (which note types, which keywords) | `assets/experience/` | **removed from the spec on 2026-08-02; nothing certified exists yet** |

Until that date the prior lived inside the spec, so the first and third could not be varied
separately. It is out now, and a run against the contract below plans over the whole chart with
no keyword or note-type prior at all.

## The tools a run has (all seven, no others)

`list_documents` (metadata only) · `document_type_summary` (every type, count, date span) ·
`search_notes` (one or many keywords, case-insensitive substring, hits attributed to the term
that found them, per-term cap) · `read_document` (offset/limit) · `read_documents_batch` ·
`record_evidence` (note_id + character offsets + what it supports) · `submit_answer`.

Deliberately ordinary. There is no semantic search, no section addressing, no timeline tool.

## What changed since the last review

An earlier version of this pack had eight cards in one slot. A review found they were not eight
comparable policies but five kinds of thing, so they now sit in the slots they belong to: a
CONTROLLER decides what to do next and one is drawn per run; a TACTIC is a move available when
its precondition holds; EXPERIENCE opens only in the experience arm; the tool contract goes to
every arm without exception. Corpus measurements, named cases and domain examples are out of all
of them — the measurements are in `assets/experience/`, labelled as observations rather than
instruction.

What we do not know is whether the remaining text is now GENERAL, or merely shorter.

The contract has also had its OUTCOME SPACE moved into it. The list of things a run may
conclude used to be a literal `enum` in the tool that submits answers and a chain of
`status == "..."` branches in the gate; a contract could not widen it, and a status nobody
declared fell through the gate to unconditional acceptance. `result.status` now names each
outcome and its KIND — value / abstain_evidence / abstain_spec / failure — and code branches
on the kind, so a new outcome arrives with obligations rather than without them. Its value
space gained the same treatment: a date is validated in two steps, a component pattern and
then a calendar, and one imputation boolean became three because one could not say which
component was estimated.

## What we would like reviewed

1. **Generality.** For each card: is this a habit that transfers to any record and any question,
   or a tactic for one situation? Where it is a tactic, what is the general policy it is a
   special case of?
2. **Rules that damage.** Not "suboptimal" — rules that would actively steer a competent reader
   away from the answer. Please quote them.
3. **Domain leakage.** Which rules are about oncology, or about clinical records specifically,
   rather than about reading a body of documents to answer a question?
4. **Overlap.** Eight cards for one slot. Which are genuinely distinct, and which are the same
   policy stated twice?
5. **What is missing.** What general search habit is not represented here at all?
6. **The contract.** Is anything in it unanswerable, self-contradictory, or unenforceable? Its
   value space in particular: can a run express everything it might truthfully need to say?

Nothing in this pack reports what we measured. The cards should be defensible as policies.

---

# 1. The task contract

`{spec_rel}`, verbatim.

```yaml
{spec_text}
```

---

# 2. The cards

Each is rendered into the system prompt whole. All are advisory: a run that departs from one is
recorded as having departed, not refused.
"""


def main() -> None:
    sha = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT,
                         capture_output=True, text=True).stdout.strip()
    print(HEAD.format(sha=sha, spec_rel=SPEC.relative_to(ROOT),
                      spec_text=SPEC.read_text(encoding="utf-8").rstrip()))
    for i, (slot, name, intent) in enumerate(CARDS, 1):
        body = (site.skills_root() / name / "SKILL.md").read_text(encoding="utf-8")
        print(f"\n---\n\n## 2.{i}  `{name}`  ·  slot: **{slot}**\n\n"
              f"**What it is trying to achieve.** {intent}\n\n"
              f"```markdown\n{body.rstrip()}\n```")


if __name__ == "__main__":
    main()
