"""Assemble the artefacts an outside reviewer needs into one file.

    python tools/make_review_pack.py > docs/REVIEW_PACK.md

Generated rather than written so the quoted artefacts are byte-identical to the tree and the
pack can be regenerated after any change. Nothing here is a summary of the artefacts — the
artefacts are pasted whole, because a reviewer asked to judge a rule needs the rule.
"""

from __future__ import annotations

import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[1]

#: `slot: search` cards only, and not the three `-nostop` variants — those are one experiment's
#: derived arms, not strategies anyone proposed.
CARDS = ["keyword-strategy", "search-native", "search-preplanned", "search-breadth-first",
         "search-depth-first", "search-breadth-then-depth", "search-information-gain",
         "search-latest-first"]

SPEC = ROOT / "assets" / "specs" / "STORE.390.date_of_initial_diagnosis.yaml"

HEAD = """# Review pack — one task contract and eight search strategies

Generated by `tools/make_review_pack.py` at commit `{sha}`. Everything below is pasted verbatim
from the repository.

## What this is

An agentic chart-review system. A model is given a **task contract** (what the answer must mean)
and a **search strategy card** (how to move through the record), plus seven tools over one
patient's documents. It reads, cites, and submits an answer.

Cancer registry abstraction is the use case under test; the architecture is meant to be
domain-neutral, so a rule that only makes sense for oncology is a defect.

**The three factors are meant to vary independently:**

| factor | where it lives | status |
|---|---|---|
| task contract | `assets/specs/*.yaml` | independent |
| search strategy | `assets/skills/search-*/SKILL.md` | independent, slot-assembled, one per run |
| prior experience (which note types, which keywords) | `assets/experience/` | **removed from the spec on 2026-08-02; nothing certified exists yet** |

Until that date the prior lived inside the spec, so the first and third could not be varied
separately. It is out now, and a run against the contract below plans over the whole chart with
no keyword or note-type prior at all.

## The tools a run has (all seven, no others)

`list_documents` (metadata only) · `document_type_summary` (every type, count, date span) ·
`search_notes` (one or many keywords, case-insensitive substring, hits attributed to the term
that found them, per-term cap) · `read_document` (offset/limit) · `read_documents_batch` ·
`record_evidence` (note_id + character offsets + what it supports) · `submit_answer`.

Deliberately ordinary. There is no semantic search, no section addressing, no timeline tool.

## Measured facts bearing on the cards

The corpus is 21 synthetic patients, ~300 documents each. Six of them (`SYNX01`–`SYNX06`) are
adversarial: each declares the wrong-but-reachable answer an ordinary pass yields, so "did the
trap spring" is countable. All numbers below are from runs on this corpus.

1. **No card beat an empty search slot.** Seven cards, eighteen charts. The empty slot scored
   15/18; every card scored at or below it.
2. **The hand-written prior cost accuracy.** With it: 12.8 documents read per patient, 3/6 on the
   adversarial charts. Without it: 5.8 read, 5/6. It read twice as much and found less — on
   `SYNX05` it read exactly the 23 documents its `exhaustive` policy mandated, 22 of them a
   decade of routine clinic notes, and never opened the one carrying the answer.
3. **On `SYNX05` the winning search term was `cancer`** — a synonym of `carcinoma` and
   `malignancy`, both of which had already returned hits.
4. **Stems beat full words.** `patholog` 11–91 hits where `pathology` gets 5–58; `bronch` 15–176
   where `bronchus` gets 13–46.
5. **Searches that lead to no read did nothing.** Across 39 early traces, 67% of searches were
   never followed by a read of anything they hit.
6. **Hit truncation no longer occurs.** 0 of 953 term-searches in the most recent runs came back
   truncated, since the cap became per-term.

## What we would like reviewed

1. **Each card, on its own terms.** Is the strategy it describes coherent? Are there rules that
   would obviously damage task execution — not "suboptimal", but actively steering away from the
   answer?
2. **Domain leakage.** Which rules are secretly about oncology rather than about reading records?
3. **The contract.** Is anything in it unanswerable, self-contradictory, or unenforceable? Its
   value space, in particular: does it let a run express everything a run might truthfully need
   to say?
4. **Overlap.** Eight cards for one slot. Which are genuinely distinct strategies and which are
   the same strategy twice?
5. **What is missing.** Given the six measured facts above, what strategy is not represented here
   at all?

---

# 1. The task contract

`{spec_rel}`, verbatim.

```yaml
{spec_text}
```

---

# 2. The eight search strategy cards

One is selected per run and rendered into the system prompt whole. They are advisory: a run that
departs from its card is recorded as having departed, not refused.
"""


def main() -> None:
    sha = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT,
                         capture_output=True, text=True).stdout.strip()
    print(HEAD.format(sha=sha, spec_rel=SPEC.relative_to(ROOT),
                      spec_text=SPEC.read_text(encoding="utf-8").rstrip()))
    for i, name in enumerate(CARDS, 1):
        body = (ROOT / "assets" / "skills" / name / "SKILL.md").read_text(encoding="utf-8")
        print(f"\n---\n\n## 2.{i}  `{name}`\n\n```markdown\n{body.rstrip()}\n```")


if __name__ == "__main__":
    main()
