"""Assemble the artefacts an outside reviewer needs into one file.

    python tools/make_review_pack.py > docs/REVIEW_PACK.md

Generated rather than written so the quoted artefacts are byte-identical to the tree and the
pack can be regenerated after any change. Nothing here is a summary of the artefacts — the
artefacts are pasted whole, because a reviewer asked to judge a rule needs the rule.
"""

from __future__ import annotations

import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[1]

#: `slot: search` cards only, and not the three `-nostop` variants — those are one experiment's
#: derived arms, not strategies anyone proposed.
#:
#: The second element is what the card is TRYING TO ACHIEVE, in our words, so a reviewer can
#: judge the text against its own intention. No result from our runs appears anywhere in this
#: pack: a policy has to be defensible as a policy, and quoting our own measurements at a
#: reviewer both prejudges the question and rests it on numbers from one synthetic corpus.
CARDS = [
    ("keyword-strategy",
     "Build the term list from what the ANSWER must say rather than from the topic of the "
     "record; prefer the shortest unambiguous form of a word; treat a search as a locator and "
     "never as a finding."),
    ("search-native",
     "When no term list has been supplied, derive terms from the contract's own words and the "
     "record's own vocabulary, widen along one axis at a time after a miss, and stop only when "
     "you can name what a further search would have to find in order to change the answer."),
    ("search-preplanned",
     "When a term list and a type prior HAVE been supplied, work them first because they are "
     "cheap, then test them against this record, and treat a disagreement between plan and "
     "record as a fact about the plan."),
    ("search-breadth-first",
     "Build the full pool of candidate documents before reading any of them, so that whatever "
     "is later claimed about the record rests on a denominator that can be stated."),
    ("search-depth-first",
     "When a document defers its own conclusion, follow the deferral to where the question was "
     "settled, rather than sampling more of the record."),
    ("search-breadth-then-depth",
     "Do both, in a stated order, using the sweep to generate the questions that the chase then "
     "answers."),
    ("search-information-gain",
     "Choose each next action by what it could change about the answer, rather than by how much "
     "of the record it covers."),
    ("search-latest-first",
     "Enter at the most recent summarising document to learn the shape of the case and its "
     "local vocabulary cheaply, then move upstream to the records that actually establish "
     "things."),
]

SPEC = ROOT / "assets" / "specs" / "STORE.390.date_of_initial_diagnosis.yaml"

HEAD = """# Review pack — one task contract and eight search strategies

Generated by `tools/make_review_pack.py` at commit `{sha}`. Everything below is pasted verbatim
from the repository.

## What this is

An agentic chart-review system. A model is given a **task contract** (what the answer must mean)
and a **search strategy card** (how to move through the record), plus seven tools over one
patient's documents. It reads, cites, and submits an answer.

Cancer registry abstraction is the use case under test; the architecture is meant to be
domain-neutral, so a rule that only makes sense for oncology is a defect.

**The three factors are meant to vary independently:**

| factor | where it lives | status |
|---|---|---|
| task contract | `assets/specs/*.yaml` | independent |
| search strategy | `assets/skills/search-*/SKILL.md` | independent, slot-assembled, one per run |
| prior experience (which note types, which keywords) | `assets/experience/` | **removed from the spec on 2026-08-02; nothing certified exists yet** |

Until that date the prior lived inside the spec, so the first and third could not be varied
separately. It is out now, and a run against the contract below plans over the whole chart with
no keyword or note-type prior at all.

## The tools a run has (all seven, no others)

`list_documents` (metadata only) · `document_type_summary` (every type, count, date span) ·
`search_notes` (one or many keywords, case-insensitive substring, hits attributed to the term
that found them, per-term cap) · `read_document` (offset/limit) · `read_documents_batch` ·
`record_evidence` (note_id + character offsets + what it supports) · `submit_answer`.

Deliberately ordinary. There is no semantic search, no section addressing, no timeline tool.

## The problem we already know these cards have, and want judged

**They are too specific to be policies.** A search policy should be a general habit of reading
records — something that tells you what to do with any question against any record. Several of
these instead read as tactics for a situation that may or may not arise, or as reports of what
happened on one corpus. Three symptoms, all of which a reviewer will see in the text below:

- **Anecdote hardened into rule.** Some cards quote counts, named patients and hit tables from
  our own runs. Whatever those numbers were worth as evidence, inside a policy they are
  instructions that only apply where the same thing happens to be true.
- **A domain's example doing a general rule's work.** Where a card needs to illustrate "a
  document that defers its own conclusion", it reaches for a pathology report awaiting stains.
  A reader in another domain has to translate before they can comply.
- **Conditional tactics presented as strategies.** Following a deferral requires a deferral to
  exist. Entering at the latest summary requires a summarising document to exist. Working a
  supplied plan requires a plan. These are moves, not policies, and a run that draws one of them
  on a record that does not meet its precondition has been handed nothing.

## What we would like reviewed

1. **Generality.** For each card: is this a habit that transfers to any record and any question,
   or a tactic for one situation? Where it is a tactic, what is the general policy it is a
   special case of?
2. **Rules that damage.** Not "suboptimal" — rules that would actively steer a competent reader
   away from the answer. Please quote them.
3. **Domain leakage.** Which rules are about oncology, or about clinical records specifically,
   rather than about reading a body of documents to answer a question?
4. **Overlap.** Eight cards for one slot. Which are genuinely distinct, and which are the same
   policy stated twice?
5. **What is missing.** What general search habit is not represented here at all?
6. **The contract.** Is anything in it unanswerable, self-contradictory, or unenforceable? Its
   value space in particular: can a run express everything it might truthfully need to say?

Nothing in this pack reports what we measured. The cards should be defensible as policies.

---

# 1. The task contract

`{spec_rel}`, verbatim.

```yaml
{spec_text}
```

---

# 2. The eight search strategy cards

One is selected per run and rendered into the system prompt whole. They are advisory: a run that
departs from its card is recorded as having departed, not refused.
"""


def main() -> None:
    sha = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT,
                         capture_output=True, text=True).stdout.strip()
    print(HEAD.format(sha=sha, spec_rel=SPEC.relative_to(ROOT),
                      spec_text=SPEC.read_text(encoding="utf-8").rstrip()))
    for i, (name, intent) in enumerate(CARDS, 1):
        body = (ROOT / "assets" / "skills" / name / "SKILL.md").read_text(encoding="utf-8")
        print(f"\n---\n\n## 2.{i}  `{name}`\n\n**What it is trying to achieve.** {intent}\n\n"
              f"```markdown\n{body.rstrip()}\n```")


if __name__ == "__main__":
    main()
